name: WebMapping
channels:
  - javascript
  - pyviz
dependencies:
  - python=3.9
  - bokeh=2.4.2
  - conda-forge::numpy=1.21.*
  - nodejs=16.13.*
  - flask
  - pip
  - pandas
  - folium
  - ipywidgets
  - matplotlib
  - widgetsnbextension
  - ipython
  - panel
  - pip:
    - Flask-Testing
packages:
- jupyter-panel-proxy
- pandas
